import { describe, it, expect } from "vitest";
import { generateHtmlReport, generateMarkdownReport } from "./html-report";
import type { MatchReport } from "@/lib/types/match";

const mockReport: MatchReport = {
  jdSummary: {
    jobTitle: "Senior Frontend Engineer",
    seniorityLevel: "Senior",
    yearsOfExperience: "5+ years",
    requiredSkillCount: 3,
    preferredSkillCount: 2,
    educationRequired: true,
    certificationRequired: false,
    summary: "Looking for a senior frontend engineer with React expertise.",
  },
  candidateOverview: [
    { candidateId: "c1", candidateName: "Alice", matchScore: 85, matchLevel: "Excellent Match", recommendation: "Strongly Recommend" },
    { candidateId: "c2", candidateName: "Bob", matchScore: 62, matchLevel: "Partial Match", recommendation: "Consider" },
  ],
  candidateAnalyses: [
    {
      candidateId: "c1",
      candidateName: "Alice",
      matchedRequirements: [{ requirement: "React", category: "skill", priority: "required", status: "matched", evidenceFromCV: "5 years React", explanation: "Strong match" }],
      partiallyMatchedRequirements: [],
      missingRequirements: [],
      strongEvidence: [],
      weaknessesOrConcerns: [],
      recruiterSummary: "Alice is an excellent candidate.",
      scoreBreakdown: {
        requiredSkills: 90, relevantExperience: 85, toolsAndPlatforms: 80,
        seniorityAndYears: 90, domainKnowledge: 85, educationAndCertifications: 80,
        softSkillsAndLanguages: 80, total: 85, explanation: "Strong overall match.",
      },
    },
    {
      candidateId: "c2",
      candidateName: "Bob",
      matchedRequirements: [],
      partiallyMatchedRequirements: [{ requirement: "React", category: "skill", priority: "required", status: "partially_matched", evidenceFromCV: "Basic React knowledge", explanation: "Partial match" }],
      missingRequirements: [{ requirement: "TypeScript", category: "skill", priority: "required", evidenceStatus: "Not found in CV" }],
      strongEvidence: [],
      weaknessesOrConcerns: ["Limited React experience"],
      recruiterSummary: "Bob needs more experience.",
      scoreBreakdown: {
        requiredSkills: 40, relevantExperience: 60, toolsAndPlatforms: 50,
        seniorityAndYears: 65, domainKnowledge: 45, educationAndCertifications: 70,
        softSkillsAndLanguages: 60, total: 62, explanation: "Partial match.",
      },
    },
  ],
  candidateRanking: [
    { rank: 1, candidateId: "c1", candidateName: "Alice", matchScore: 85, matchLevel: "Excellent Match", recommendation: "Strongly Recommend", rationale: "Strongest skill alignment." },
    { rank: 2, candidateId: "c2", candidateName: "Bob", matchScore: 62, matchLevel: "Partial Match", recommendation: "Consider", rationale: "Lacks key skills." },
  ],
  finalRecommendation: {
    topCandidateId: "c1", topCandidateName: "Alice", topCandidateScore: 85, totalCandidates: 2,
    explanation: "Alice is the strongest match.",
    hiringAdvice: "Proceed with interview.",
  },
};

describe("generateHtmlReport", () => {
  it("returns a complete HTML document", () => {
    const html = generateHtmlReport(mockReport);
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("</html>");
  });

  it("includes the job title in the title tag", () => {
    const html = generateHtmlReport(mockReport);
    expect(html).toContain("Senior Frontend Engineer");
  });

  it("includes candidate names and scores", () => {
    const html = generateHtmlReport(mockReport);
    expect(html).toContain("Alice");
    expect(html).toContain("Bob");
    expect(html).toContain("85/100");
    expect(html).toContain("62/100");
  });

  it("includes score breakdowns for each candidate", () => {
    const html = generateHtmlReport(mockReport);
    expect(html).toContain("Excellent Match");
    expect(html).toContain("Partial Match");
    expect(html).toContain("Strongly Recommend");
    expect(html).toContain("Consider");
  });

  it("includes final recommendation", () => {
    const html = generateHtmlReport(mockReport);
    expect(html).toContain("Top Candidate");
    expect(html).toContain("Proceed with interview");
  });

  it("includes inline CSS styles", () => {
    const html = generateHtmlReport(mockReport);
    expect(html).toContain("<style>");
    expect(html).toContain(".bar-bg");
    expect(html).toContain(".card");
  });

  it("includes generated-by footer", () => {
    const html = generateHtmlReport(mockReport);
    expect(html).toContain("Generated by Atlas Match");
  });
});

describe("generateMarkdownReport", () => {
  it("returns a complete markdown document", () => {
    const md = generateMarkdownReport(mockReport);
    expect(md).toContain("# Atlas Match");
    expect(md).toContain("Candidate Overview");
    expect(md).toContain("Final Recommendation");
  });

  it("includes candidate details", () => {
    const md = generateMarkdownReport(mockReport);
    expect(md).toContain("Alice");
    expect(md).toContain("Bob");
    expect(md).toContain("85/100");
    expect(md).toContain("62/100");
  });

  it("includes matched and missing requirements", () => {
    const md = generateMarkdownReport(mockReport);
    expect(md).toContain("Matched Requirements");
    expect(md).toContain("Missing Requirements");
    expect(md).toContain("TypeScript");
  });

  it("includes concerns", () => {
    const md = generateMarkdownReport(mockReport);
    expect(md).toContain("Limited React experience");
  });

  it("includes ranking table", () => {
    const md = generateMarkdownReport(mockReport);
    expect(md).toContain("Candidate Ranking");
    expect(md).toContain("Strongest skill alignment");
  });

  it("includes hiring advice", () => {
    const md = generateMarkdownReport(mockReport);
    expect(md).toContain("Proceed with interview");
  });
});
