import type { MatchReport } from "@/lib/types/match";

/**
 * Generate a standalone HTML report from a MatchReport.
 * Inline CSS for zero-dependency portability.
 */
export function generateHtmlReport(report: MatchReport): string {
  const scoreBar = (score: number) =>
    `<div class="bar-bg"><div class="bar-fill" style="width:${score}%"></div></div><span class="val">${score}/100</span>`;

  const { jdSummary, candidateOverview, candidateAnalyses, candidateRanking, finalRecommendation } = report;

  let html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Atlas Match Report — ${jdSummary.jobTitle ?? "Job Analysis"}</title>
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;font-size:13px;color:#1a1a2e;padding:40px;background:#f8fafc}
  h1{font-size:22px;font-weight:700;margin-bottom:4px}
  h2{font-size:16px;font-weight:600;margin-top:24px;margin-bottom:12px;border-bottom:2px solid #e2e8f0;padding-bottom:6px}
  h3{font-size:14px;font-weight:600;margin-top:16px;margin-bottom:8px}
  .meta{color:#64748b;font-size:11px;margin-bottom:24px}
  table{width:100%;border-collapse:collapse;margin:12px 0}
  th,td{text-align:left;padding:8px 12px;border-bottom:1px solid #e2e8f0}
  th{background:#f1f5f9;font-weight:600;font-size:11px;text-transform:uppercase;color:#64748b}
  .bar-bg{display:inline-block;width:120px;height:10px;background:#e2e8f0;border-radius:5px;vertical-align:middle}
  .bar-fill{height:100%;border-radius:5px;background:linear-gradient(90deg,#3b82f6,#2563eb)}
  .val{margin-left:8px;font-weight:600;font-size:11px;color:#475569}
  .card{border:1px solid #e2e8f0;border-radius:10px;padding:20px;margin-bottom:16px;background:#fff}
  .score-row{display:flex;align-items:center;gap:8px;padding:4px 0}
  .score-label{width:100px;font-size:12px;color:#64748b}
  .tag{display:inline-block;padding:2px 10px;border-radius:5px;font-size:11px;font-weight:500}
  .green{background:#dcfce7;color:#166534}
  .blue{background:#dbeafe;color:#1e40af}
  .amber{background:#fef3c7;color:#92400e}
  .summary{color:#475569;font-size:12px;line-height:1.6;margin-top:8px}
  .rec{border-left:4px solid #16a34a;padding:12px 16px;background:#f0fdf4;border-radius:8px;margin-top:16px}
  .footer{margin-top:32px;padding-top:16px;border-top:1px solid #e2e8f0;font-size:10px;color:#94a3b8;text-align:center}
</style></head><body>
  <h1>Atlas Match Report</h1>
  <div class="meta"><strong>${jdSummary.jobTitle ?? "N/A"}</strong>${jdSummary.seniorityLevel ? " · "+jdSummary.seniorityLevel : ""}${jdSummary.yearsOfExperience ? " · "+jdSummary.yearsOfExperience+"+ years" : ""} · ${new Date().toLocaleDateString()}</div>
  <p style="margin-bottom:16px;color:#475569">${jdSummary.summary}</p>

  <h2>Candidate Overview</h2>
  <table><tr><th>Rank</th><th>Name</th><th>Score</th><th>Level</th><th>Recommendation</th></tr>`;

  for (const r of candidateRanking) {
    const tagClass = r.recommendation === "Strongly Recommend" || r.recommendation === "Recommend" ? "green" : r.recommendation === "Consider" ? "amber" : "";
    html += `<tr><td>#${r.rank}</td><td><strong>${r.candidateName ?? "Unknown"}</strong></td><td>${scoreBar(r.matchScore)}</td><td><span class="tag blue">${r.matchLevel}</span></td><td><span class="tag ${tagClass}">${r.recommendation}</span></td></tr>`;
  }

  html += `</table>`;

  for (const ca of candidateAnalyses) {
    const rank = candidateRanking.find(r => r.candidateId === ca.candidateId);
    const name = ca.candidateName ?? "Unknown";
    html += `<div class="card"><h3>#${rank?.rank ?? "?"} ${name} — ${ca.scoreBreakdown.total}/100</h3>`;
    html += `<div class="score-row"><span class="score-label">Skills</span>${scoreBar(ca.scoreBreakdown.requiredSkills)}</div>`;
    html += `<div class="score-row"><span class="score-label">Experience</span>${scoreBar(ca.scoreBreakdown.relevantExperience)}</div>`;
    html += `<div class="score-row"><span class="score-label">Tools</span>${scoreBar(ca.scoreBreakdown.toolsAndPlatforms)}</div>`;
    html += `<div class="score-row"><span class="score-label">Seniority</span>${scoreBar(ca.scoreBreakdown.seniorityAndYears)}</div>`;
    html += `<div class="score-row"><span class="score-label">Education</span>${scoreBar(ca.scoreBreakdown.educationAndCertifications)}</div>`;
    html += `<p class="summary">${ca.recruiterSummary}</p></div>`;
  }

  html += `<h2>Final Recommendation</h2><div class="rec">`;
  if (finalRecommendation.topCandidateName) {
    html += `<strong>Top Candidate:</strong> ${finalRecommendation.topCandidateName} (${finalRecommendation.topCandidateScore}/100)<br>`;
  }
  html += `${finalRecommendation.explanation}<br><br><strong>Advice:</strong> ${finalRecommendation.hiringAdvice}`;
  html += `</div><div class="footer">Generated by Atlas Match — evidence-first candidate screening</div></body></html>`;

  return html;
}

/**
 * Generate a Markdown report from a MatchReport.
 */
export function generateMarkdownReport(report: MatchReport): string {
  let md = `# Atlas Match — Candidate Analysis Report\n\n`;
  md += `**Generated**: ${new Date().toLocaleString()}\n\n`;

  md += `## JD Summary\n\n`;
  md += `**${report.jdSummary.jobTitle || "Unknown Role"}**`;
  if (report.jdSummary.seniorityLevel) md += ` — ${report.jdSummary.seniorityLevel}`;
  md += `\n\n`;
  if (report.jdSummary.yearsOfExperience) md += `- **Experience**: ${report.jdSummary.yearsOfExperience}\n`;
  md += `- **Required Skills**: ${report.jdSummary.requiredSkillCount}\n`;
  md += `- **Preferred Skills**: ${report.jdSummary.preferredSkillCount}\n`;
  if (report.jdSummary.educationRequired) md += `- **Education Required**: Yes\n`;
  md += `\n${report.jdSummary.summary}\n\n`;

  md += `## Candidate Overview\n\n`;
  md += `| Rank | Name | Score | Match Level | Recommendation |\n`;
  md += `| --- | --- | --- | --- | --- |\n`;
  report.candidateRanking.forEach((c) => {
    md += `| ${c.rank} | ${c.candidateName || "Unnamed"} | ${c.matchScore}/100 | ${c.matchLevel} | ${c.recommendation} |\n`;
  });
  md += `\n`;

  report.candidateAnalyses.forEach((analysis, i) => {
    const rank = report.candidateRanking.find((r) => r.candidateId === analysis.candidateId);
    md += `## ${rank ? `#${rank.rank}: ` : ""}${analysis.candidateName || `Candidate ${i + 1}`}\n\n`;
    md += `**Score**: ${analysis.scoreBreakdown.total}/100\n\n`;
    md += `**Score Breakdown**:\n`;
    md += `- Required Skills: ${analysis.scoreBreakdown.requiredSkills}/100\n`;
    md += `- Experience: ${analysis.scoreBreakdown.relevantExperience}/100\n`;
    md += `- Tools & Platforms: ${analysis.scoreBreakdown.toolsAndPlatforms}/100\n`;
    md += `- Education & Certs: ${analysis.scoreBreakdown.educationAndCertifications}/100\n`;
    md += `- Soft Skills: ${analysis.scoreBreakdown.softSkillsAndLanguages}/100\n\n`;

    if (analysis.matchedRequirements.length > 0) {
      md += `### ✅ Matched Requirements\n\n`;
      analysis.matchedRequirements.forEach((r) => {
        md += `- **${r.requirement}** (${r.priority}): ${r.explanation}\n`;
      });
      md += `\n`;
    }

    if (analysis.partiallyMatchedRequirements.length > 0) {
      md += `### ⚠️ Partially Matched\n\n`;
      analysis.partiallyMatchedRequirements.forEach((r) => {
        md += `- **${r.requirement}** (${r.priority}): ${r.explanation}\n`;
      });
      md += `\n`;
    }

    if (analysis.missingRequirements.length > 0) {
      md += `### ❌ Missing Requirements\n\n`;
      analysis.missingRequirements.forEach((r) => {
        md += `- **${r.requirement}** (${r.priority}): ${r.evidenceStatus}\n`;
      });
      md += `\n`;
    }

    if (analysis.weaknessesOrConcerns.length > 0) {
      md += `### ⚡ Concerns\n\n`;
      analysis.weaknessesOrConcerns.forEach((c) => {
        md += `- ${c}\n`;
      });
      md += `\n`;
    }

    md += `### Summary\n\n${analysis.recruiterSummary}\n\n`;
    md += `---\n\n`;
  });

  md += `## Final Recommendation\n\n`;
  if (report.finalRecommendation.topCandidateName) {
    md += `**Top Candidate**: ${report.finalRecommendation.topCandidateName} (${report.finalRecommendation.topCandidateScore}/100)\n\n`;
  }
  md += `${report.finalRecommendation.explanation}\n\n`;
  md += `**Advice**: ${report.finalRecommendation.hiringAdvice}\n\n`;

  md += `## Candidate Ranking\n\n`;
  md += `| Rank | Name | Score | Rationale |\n`;
  md += `| --- | --- | --- | --- |\n`;
  report.candidateRanking.forEach((c) => {
    md += `| ${c.rank} | ${c.candidateName || "Unnamed"} | ${c.matchScore}/100 | ${c.rationale} |\n`;
  });

  return md;
}
